<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipalities = [
            ["id" => 1, "state_id" => 7,"name" => "Acacoyagua", "activo" => true,],
            ["id" => 2, "state_id" => 7,"name" => "Acala", "activo" => true,],
            ["id" => 3, "state_id" => 7,"name" => "Acapetahua", "activo" => true,],
            ["id" => 4, "state_id" => 7,"name" => "Altamirano", "activo" => true,],
            ["id" => 5, "state_id" => 7,"name" => "Amatán", "activo" => true,],
            ["id" => 6, "state_id" => 7,"name" => "Amatenango de la Frontera", "activo" => true,],
            ["id" => 7, "state_id" => 7,"name" => "Amatenango del Valle", "activo" => true,],
            ["id" => 8, "state_id" => 7,"name" => "Angel Albino Corzo", "activo" => true,],
            ["id" => 9, "state_id" => 7,"name" => "Arriaga", "activo" => true,],
            ["id" => 10, "state_id" => 7,"name" => "Bejucal de Ocampo", "activo" => true,],
            ["id" => 11, "state_id" => 7,"name" => "Bella Vista", "activo" => true,],
            ["id" => 12, "state_id" => 7,"name" => "Berriozábal", "activo" => true,],
            ["id" => 13, "state_id" => 7,"name" => "Bochil", "activo" => true,],
            ["id" => 14, "state_id" => 7,"name" => "El Bosque", "activo" => true,],
            ["id" => 15, "state_id" => 7,"name" => "Cacahoatán", "activo" => true,],
            ["id" => 16, "state_id" => 7,"name" => "Catazajá", "activo" => true,],
            ["id" => 17, "state_id" => 7,"name" => "Cintalapa", "activo" => true,],
            ["id" => 18, "state_id" => 7,"name" => "Coapilla", "activo" => true,],
            ["id" => 19, "state_id" => 7,"name" => "Comitán de Domínguez", "activo" => true,],
            ["id" => 20, "state_id" => 7,"name" => "La Concordia", "activo" => true,],
            ["id" => 21, "state_id" => 7,"name" => "Copainalá", "activo" => true,],
            ["id" => 22, "state_id" => 7,"name" => "Chalchihuitán", "activo" => true,],
            ["id" => 23, "state_id" => 7,"name" => "Chamula", "activo" => true,],
            ["id" => 24, "state_id" => 7,"name" => "Chanal", "activo" => true,],
            ["id" => 25, "state_id" => 7,"name" => "Chapultenango", "activo" => true,],
            ["id" => 26, "state_id" => 7,"name" => "Chenalhó", "activo" => true,],
            ["id" => 27, "state_id" => 7,"name" => "Chiapa de Corzo", "activo" => true,],
            ["id" => 28, "state_id" => 7,"name" => "Chiapilla", "activo" => true,],
            ["id" => 29, "state_id" => 7,"name" => "Chicoasén", "activo" => true,],
            ["id" => 30, "state_id" => 7,"name" => "Chicomuselo", "activo" => true,],
            ["id" => 31, "state_id" => 7,"name" => "Chilón", "activo" => true,],
            ["id" => 32, "state_id" => 7,"name" => "Escuintla", "activo" => true,],
            ["id" => 33, "state_id" => 7,"name" => "Francisco León", "activo" => true,],
            ["id" => 34, "state_id" => 7,"name" => "Frontera Comalapa", "activo" => true,],
            ["id" => 35, "state_id" => 7,"name" => "Frontera Hidalgo", "activo" => true,],
            ["id" => 36, "state_id" => 7,"name" => "La Grandeza", "activo" => true,],
            ["id" => 37, "state_id" => 7,"name" => "Huehuetán", "activo" => true,],
            ["id" => 38, "state_id" => 7,"name" => "Huixtán", "activo" => true,],
            ["id" => 39, "state_id" => 7,"name" => "Huitiupán", "activo" => true,],
            ["id" => 40, "state_id" => 7,"name" => "Huixtla", "activo" => true,],
            ["id" => 41, "state_id" => 7,"name" => "La Independencia", "activo" => true,],
            ["id" => 42, "state_id" => 7,"name" => "Ixhuatán", "activo" => true,],
            ["id" => 43, "state_id" => 7,"name" => "Ixtacomitán", "activo" => true,],
            ["id" => 44, "state_id" => 7,"name" => "Ixtapa", "activo" => true,],
            ["id" => 45, "state_id" => 7,"name" => "Ixtapangajoya", "activo" => true,],
            ["id" => 46, "state_id" => 7,"name" => "Jiquipilas", "activo" => true,],
            ["id" => 47, "state_id" => 7,"name" => "Jitotol", "activo" => true,],
            ["id" => 48, "state_id" => 7,"name" => "Juárez", "activo" => true,],
            ["id" => 49, "state_id" => 7,"name" => "Larráinzar", "activo" => true,],
            ["id" => 50, "state_id" => 7,"name" => "La Libertad", "activo" => true,],
            ["id" => 51, "state_id" => 7,"name" => "Mapastepec", "activo" => true,],
            ["id" => 52, "state_id" => 7,"name" => "Las Margaritas", "activo" => true,],
            ["id" => 53, "state_id" => 7,"name" => "Mazapa de Madero", "activo" => true,],
            ["id" => 54, "state_id" => 7,"name" => "Mazatán", "activo" => true,],
            ["id" => 55, "state_id" => 7,"name" => "Metapa", "activo" => true,],
            ["id" => 56, "state_id" => 7,"name" => "Mitontic", "activo" => true,],
            ["id" => 57, "state_id" => 7,"name" => "Motozintla", "activo" => true,],
            ["id" => 58, "state_id" => 7,"name" => "Nicolás Ruíz", "activo" => true,],
            ["id" => 59, "state_id" => 7,"name" => "Ocosingo", "activo" => true,],
            ["id" => 60, "state_id" => 7,"name" => "Ocotepec", "activo" => true,],
            ["id" => 61, "state_id" => 7,"name" => "Ocozocoautla de Espinosa", "activo" => true,],
            ["id" => 62, "state_id" => 7,"name" => "Ostuacán", "activo" => true,],
            ["id" => 63, "state_id" => 7,"name" => "Osumacinta", "activo" => true,],
            ["id" => 64, "state_id" => 7,"name" => "Oxchuc", "activo" => true,],
            ["id" => 65, "state_id" => 7,"name" => "Palenque", "activo" => true,],
            ["id" => 66, "state_id" => 7,"name" => "Pantelhó", "activo" => true,],
            ["id" => 67, "state_id" => 7,"name" => "Pantepec", "activo" => true,],
            ["id" => 68, "state_id" => 7,"name" => "Pichucalco", "activo" => true,],
            ["id" => 69, "state_id" => 7,"name" => "Pijijiapan", "activo" => true,],
            ["id" => 70, "state_id" => 7,"name" => "El Porvenir", "activo" => true,],
            ["id" => 71, "state_id" => 7,"name" => "Villa Comaltitlán", "activo" => true,],
            ["id" => 72, "state_id" => 7,"name" => "Pueblo Nuevo Solistahuacán", "activo" => true,],
            ["id" => 73, "state_id" => 7,"name" => "Rayón", "activo" => true,],
            ["id" => 74, "state_id" => 7,"name" => "Reforma", "activo" => true,],
            ["id" => 75, "state_id" => 7,"name" => "Las Rosas", "activo" => true,],
            ["id" => 76, "state_id" => 7,"name" => "Sabanilla", "activo" => true,],
            ["id" => 77, "state_id" => 7,"name" => "Salto de Agua", "activo" => true,],
            ["id" => 78, "state_id" => 7,"name" => "San Cristóbal de las Casas", "activo" => true,],
            ["id" => 79, "state_id" => 7,"name" => "San Fernando", "activo" => true,],
            ["id" => 80, "state_id" => 7,"name" => "Siltepec", "activo" => true,],
            ["id" => 81, "state_id" => 7,"name" => "Simojovel", "activo" => true,],
            ["id" => 82, "state_id" => 7,"name" => "Sitalá", "activo" => true,],
            ["id" => 83, "state_id" => 7,"name" => "Socoltenango", "activo" => true,],
            ["id" => 84, "state_id" => 7,"name" => "Solosuchiapa", "activo" => true,],
            ["id" => 85, "state_id" => 7,"name" => "Soyaló", "activo" => true,],
            ["id" => 86, "state_id" => 7,"name" => "Suchiapa", "activo" => true,],
            ["id" => 87, "state_id" => 7,"name" => "Suchiate", "activo" => true,],
            ["id" => 88, "state_id" => 7,"name" => "Sunuapa", "activo" => true,],
            ["id" => 89, "state_id" => 7,"name" => "Tapachula de Córdova y Ordoñez", "activo" => true,],
            ["id" => 90, "state_id" => 7,"name" => "Tapalapa", "activo" => true,],
            ["id" => 91, "state_id" => 7,"name" => "Tapilula", "activo" => true,],
            ["id" => 92, "state_id" => 7,"name" => "Tecpatán", "activo" => true,],
            ["id" => 93, "state_id" => 7,"name" => "Tenejapa", "activo" => true,],
            ["id" => 94, "state_id" => 7,"name" => "Teopisca", "activo" => true,],
            ["id" => 95, "state_id" => 7,"name" => "Tila", "activo" => true,],
            ["id" => 96, "state_id" => 7,"name" => "Tonalá", "activo" => true,],
            ["id" => 97, "state_id" => 7,"name" => "Totolapa", "activo" => true,],
            ["id" => 98, "state_id" => 7,"name" => "La Trinitaria", "activo" => true,],
            ["id" => 99, "state_id" => 7,"name" => "Tumbalá", "activo" => true,],
            ["id" => 100, "state_id" => 7,"name" => "Tuxtla Gutiérrez", "activo" => true,],
            ["id" => 101, "state_id" => 7,"name" => "Tuxtla Chico", "activo" => true,],
            ["id" => 102, "state_id" => 7,"name" => "Tuzantán", "activo" => true,],
            ["id" => 103, "state_id" => 7,"name" => "Tzimol", "activo" => true,],
            ["id" => 104, "state_id" => 7,"name" => "Unión Juárez", "activo" => true,],
            ["id" => 105, "state_id" => 7,"name" => "Venustiano Carranza", "activo" => true,],
            ["id" => 106, "state_id" => 7,"name" => "Villa Corzo", "activo" => true,],
            ["id" => 107, "state_id" => 7,"name" => "Villaflores", "activo" => true,],
            ["id" => 108, "state_id" => 7,"name" => "Yajalón", "activo" => true,],
            ["id" => 109, "state_id" => 7,"name" => "San Lucas", "activo" => true,],
            ["id" => 110, "state_id" => 7,"name" => "Zinacantán", "activo" => true,],
            ["id" => 111, "state_id" => 7,"name" => "San Juan Cancuc", "activo" => true,],
            ["id" => 112, "state_id" => 7,"name" => "Aldama", "activo" => true,],
            ["id" => 113, "state_id" => 7,"name" => "Benemérito de las Américas", "activo" => true,],
            ["id" => 114, "state_id" => 7,"name" => "Maravilla Tenejapa", "activo" => true,],
            ["id" => 115, "state_id" => 7,"name" => "Marqués de Comillas", "activo" => true,],
            ["id" => 116, "state_id" => 7,"name" => "Montecristo de Guerrero", "activo" => true,],
            ["id" => 117, "state_id" => 7,"name" => "San Andrés Duraznal", "activo" => true,],
            ["id" => 118, "state_id" => 7,"name" => "Santiago el Pinar", "activo" => true,],
            ["id" => 119, "state_id" => 20,"name" => "San Juan Bautista Tuxtepec", "activo" => true,],
            ["id" => 120, "state_id" => 20,"name" => "Abejones", "activo" => true,],
            ["id" => 121, "state_id" => 20,"name" => "Acatlán de Pérez Figueroa", "activo" => true,],
            ["id" => 122, "state_id" => 20,"name" => "Animas Trujano", "activo" => true,],
            ["id" => 123, "state_id" => 20,"name" => "Asunción Cacalotepec", "activo" => true,],
            ["id" => 124, "state_id" => 20,"name" => "Asunción Ixtaltepec", "activo" => true,],
            ["id" => 125, "state_id" => 20,"name" => "Asunción Nochixtlán", "activo" => true,],
            ["id" => 126, "state_id" => 20,"name" => "Asunción Ocotlán", "activo" => true,],
            ["id" => 127, "state_id" => 20,"name" => "Asunción Tlacolulita", "activo" => true,],
            ["id" => 128, "state_id" => 20,"name" => "Ayoquezco de Aldama", "activo" => true,],
            ["id" => 129, "state_id" => 20,"name" => "Ayotzintepec", "activo" => true,],
            ["id" => 130, "state_id" => 20,"name" => "Calihualá", "activo" => true,],
            ["id" => 131, "state_id" => 20,"name" => "Candelaria Loxicha", "activo" => true,],
            ["id" => 132, "state_id" => 20,"name" => "Capulálpam de Méndez", "activo" => true,],
            ["id" => 133, "state_id" => 20,"name" => "Chahuites", "activo" => true,],
            ["id" => 134, "state_id" => 20,"name" => "Chalcatongo de Hidalgo", "activo" => true,],
            ["id" => 135, "state_id" => 20,"name" => "Chiquihuitlán de Benito Juárez", "activo" => true,],
            ["id" => 136, "state_id" => 20,"name" => "Ciénega de Zimatlán", "activo" => true,],
            ["id" => 137, "state_id" => 20,"name" => "Ciudad Ixtepec", "activo" => true,],
            ["id" => 138, "state_id" => 20,"name" => "Coatecas Altas", "activo" => true,],
            ["id" => 139, "state_id" => 20,"name" => "Coicoyán de las Flores", "activo" => true,],
            ["id" => 140, "state_id" => 20,"name" => "Concepción Buenavista", "activo" => true,],
            ["id" => 141, "state_id" => 20,"name" => "Constancia del Rosario", "activo" => true,],
            ["id" => 142, "state_id" => 20,"name" => "Cosolapa", "activo" => true,],
            ["id" => 143, "state_id" => 20,"name" => "Cosoltepec", "activo" => true,],
            ["id" => 144, "state_id" => 20,"name" => "Cuilápam de Guerrero", "activo" => true,],
            ["id" => 145, "state_id" => 1,"name" => "Aguascalientes", "activo" => true,],
            ["id" => 146, "state_id" => 1,"name" => "Real de Asientos", "activo" => true,],
            ["id" => 147, "state_id" => 1,"name" => "Calvillo", "activo" => true,],
            ["id" => 148, "state_id" => 1,"name" => "Cosío", "activo" => true,],
            ["id" => 149, "state_id" => 1,"name" => "El Llano", "activo" => true,],
            ["id" => 150, "state_id" => 1,"name" => "Jesús María", "activo" => true,],
            ["id" => 151, "state_id" => 1,"name" => "Pabellón de Arteaga", "activo" => true,],
            ["id" => 152, "state_id" => 1,"name" => "Rincón de Romos", "activo" => true,],
            ["id" => 153, "state_id" => 1,"name" => "San Francisco de los Romo", "activo" => true,],
            ["id" => 154, "state_id" => 1,"name" => "San José de Gracia", "activo" => true,],
            ["id" => 155, "state_id" => 1,"name" => "Tepezalá", "activo" => true,],
            ["id" => 156, "state_id" => 2,"name" => "Ensenada", "activo" => true,],
            ["id" => 157, "state_id" => 2,"name" => "Mexicali", "activo" => true,],
            ["id" => 158, "state_id" => 2,"name" => "Playas de Rosarito", "activo" => true,],
            ["id" => 159, "state_id" => 2,"name" => "Tecate", "activo" => true,],
            ["id" => 160, "state_id" => 2,"name" => "Tijuana", "activo" => true,],
            ["id" => 161, "state_id" => 3,"name" => "Comondú", "activo" => true,],
            ["id" => 162, "state_id" => 3,"name" => "La Paz", "activo" => true,],
            ["id" => 163, "state_id" => 3,"name" => "Loreto", "activo" => true,],
            ["id" => 164, "state_id" => 3,"name" => "Los Cabos", "activo" => true,],
            ["id" => 165, "state_id" => 3,"name" => "Mulegé", "activo" => true,],
            ["id" => 166, "state_id" => 4,"name" => "Calakmul", "activo" => true,],
            ["id" => 167, "state_id" => 4,"name" => "Calkiní", "activo" => true,],
            ["id" => 168, "state_id" => 4,"name" => "Campeche", "activo" => true,],
            ["id" => 169, "state_id" => 4,"name" => "Candelaria", "activo" => true,],
            ["id" => 170, "state_id" => 4,"name" => "Carmen", "activo" => true,],
            ["id" => 171, "state_id" => 4,"name" => "Champotón", "activo" => true,],
            ["id" => 172, "state_id" => 4,"name" => "Escárcega", "activo" => true,],
            ["id" => 173, "state_id" => 4,"name" => "Hecelchakán", "activo" => true,],
            ["id" => 174, "state_id" => 4,"name" => "Hopelchén", "activo" => true,],
            ["id" => 175, "state_id" => 4,"name" => "Palizada", "activo" => true,],
            ["id" => 176, "state_id" => 4,"name" => "Tenabo", "activo" => true,],
            ["id" => 177, "state_id" => 5,"name" => "Abasolo", "activo" => true,],
            ["id" => 178, "state_id" => 5,"name" => "Acuña", "activo" => true,],
            ["id" => 179, "state_id" => 5,"name" => "Allende", "activo" => true,],
            ["id" => 180, "state_id" => 5,"name" => "Arteaga", "activo" => true,],
            ["id" => 181, "state_id" => 5,"name" => "Candela", "activo" => true,],
            ["id" => 182, "state_id" => 5,"name" => "Castaños", "activo" => true,],
            ["id" => 183, "state_id" => 5,"name" => "Cuatrociénegas", "activo" => true,],
            ["id" => 184, "state_id" => 5,"name" => "Escobedo", "activo" => true,],
            ["id" => 185, "state_id" => 5,"name" => "Francisco I. Madero", "activo" => true,],
            ["id" => 186, "state_id" => 5,"name" => "Frontera", "activo" => true,],
            ["id" => 187, "state_id" => 5,"name" => "General Cepeda", "activo" => true,],
            ["id" => 188, "state_id" => 5,"name" => "Guerrero", "activo" => true,],
            ["id" => 189, "state_id" => 5,"name" => "Hidalgo", "activo" => true,],
            ["id" => 190, "state_id" => 5,"name" => "Jiménez", "activo" => true,],
            ["id" => 191, "state_id" => 5,"name" => "Juárez", "activo" => true,],
            ["id" => 192, "state_id" => 5,"name" => "Lamadrid", "activo" => true,],
            ["id" => 193, "state_id" => 5,"name" => "Matamoros", "activo" => true,],
            ["id" => 194, "state_id" => 5,"name" => "Monclova", "activo" => true,],
            ["id" => 195, "state_id" => 5,"name" => "Morelos", "activo" => true,],
            ["id" => 196, "state_id" => 5,"name" => "Múzquiz", "activo" => true,],
            ["id" => 197, "state_id" => 5,"name" => "Nadadores", "activo" => true,],
            ["id" => 198, "state_id" => 5,"name" => "Nava", "activo" => true,],
            ["id" => 199, "state_id" => 5,"name" => "Ocampo", "activo" => true,],
            ["id" => 200, "state_id" => 5,"name" => "Parras de la Fuente", "activo" => true,],
            ["id" => 201, "state_id" => 5,"name" => "Piedras Negras", "activo" => true,],
            ["id" => 202, "state_id" => 5,"name" => "Progreso", "activo" => true,],
            ["id" => 203, "state_id" => 5,"name" => "Ramos Arizpe", "activo" => true,],
            ["id" => 204, "state_id" => 5,"name" => "Sabinas", "activo" => true,],
            ["id" => 205, "state_id" => 5,"name" => "Sacramento", "activo" => true,],
            ["id" => 206, "state_id" => 5,"name" => "Saltillo", "activo" => true,],
            ["id" => 207, "state_id" => 5,"name" => "San Buenaventura", "activo" => true,],
            ["id" => 208, "state_id" => 5,"name" => "San Juan de Sabinas", "activo" => true,],
            ["id" => 209, "state_id" => 5,"name" => "San Pedro", "activo" => true,],
            ["id" => 210, "state_id" => 5,"name" => "Sierra Mojada", "activo" => true,],
            ["id" => 211, "state_id" => 5,"name" => "Torreón", "activo" => true,],
            ["id" => 212, "state_id" => 5,"name" => "Viesca", "activo" => true,],
            ["id" => 213, "state_id" => 5,"name" => "Villa Unión", "activo" => true,],
            ["id" => 214, "state_id" => 5,"name" => "Zaragoza", "activo" => true,],
            ["id" => 215, "state_id" => 6,"name" => "Armería", "activo" => true,],
            ["id" => 216, "state_id" => 6,"name" => "Colima", "activo" => true,],
            ["id" => 217, "state_id" => 6,"name" => "Comala", "activo" => true,],
            ["id" => 218, "state_id" => 6,"name" => "Coquimatlán", "activo" => true,],
            ["id" => 219, "state_id" => 6,"name" => "Cuauhtémoc", "activo" => true,],
            ["id" => 220, "state_id" => 6,"name" => "Ixtlahuacán", "activo" => true,],
            ["id" => 221, "state_id" => 6,"name" => "Manzanillo", "activo" => true,],
            ["id" => 222, "state_id" => 6,"name" => "Minatitlán", "activo" => true,],
            ["id" => 223, "state_id" => 6,"name" => "Tecomán", "activo" => true,],
            ["id" => 224, "state_id" => 6,"name" => "Villa de Álvarez", "activo" => true,],
            ["id" => 225, "state_id" => 20,"name" => "Juchitán de Zaragoza", "activo" => true,],
            ["id" => 226, "state_id" => 20,"name" => "La Compañía", "activo" => true,],
            ["id" => 227, "state_id" => 20,"name" => "La Reforma", "activo" => true,],
            ["id" => 228, "state_id" => 20,"name" => "La Trinidad Vista Hermosa", "activo" => true,],
            ["id" => 229, "state_id" => 20,"name" => "Loma Bonita", "activo" => true,],
            ["id" => 230, "state_id" => 8,"name" => "Ahumada", "activo" => true,],
            ["id" => 231, "state_id" => 8,"name" => "Aldama", "activo" => true,],
            ["id" => 232, "state_id" => 8,"name" => "Allende", "activo" => true,],
            ["id" => 233, "state_id" => 8,"name" => "Aquiles Serdán", "activo" => true,],
            ["id" => 234, "state_id" => 8,"name" => "Ascensión", "activo" => true,],
            ["id" => 235, "state_id" => 8,"name" => "Bachíniva", "activo" => true,],
            ["id" => 236, "state_id" => 8,"name" => "Balleza", "activo" => true,],
            ["id" => 237, "state_id" => 8,"name" => "Batopilas", "activo" => true,],
            ["id" => 238, "state_id" => 8,"name" => "Bocoyna", "activo" => true,],
            ["id" => 239, "state_id" => 8,"name" => "Buenaventura", "activo" => true,],
            ["id" => 240, "state_id" => 8,"name" => "Camargo", "activo" => true,],
            ["id" => 241, "state_id" => 8,"name" => "Carichí", "activo" => true,],
            ["id" => 242, "state_id" => 8,"name" => "Casas Grandes", "activo" => true,],
            ["id" => 243, "state_id" => 8,"name" => "Chihuahua", "activo" => true,],
            ["id" => 244, "state_id" => 8,"name" => "Chínipas", "activo" => true,],
            ["id" => 245, "state_id" => 8,"name" => "Coronado", "activo" => true,],
            ["id" => 246, "state_id" => 8,"name" => "Coyame del Sotol", "activo" => true,],
            ["id" => 247, "state_id" => 8,"name" => "Cuauhtémoc", "activo" => true,],
            ["id" => 248, "state_id" => 8,"name" => "Cusihuiriachi", "activo" => true,],
            ["id" => 249, "state_id" => 8,"name" => "Delicias", "activo" => true,],
            ["id" => 250, "state_id" => 8,"name" => "Dr. Belisario Domínguez", "activo" => true,],
            ["id" => 251, "state_id" => 8,"name" => "El Tule", "activo" => true,],
            ["id" => 252, "state_id" => 8,"name" => "Galeana", "activo" => true,],
            ["id" => 253, "state_id" => 8,"name" => "Gómez Farías", "activo" => true,],
            ["id" => 254, "state_id" => 8,"name" => "Gran Morelos", "activo" => true,],
            ["id" => 255, "state_id" => 8,"name" => "Guachochi", "activo" => true,],
            ["id" => 256, "state_id" => 8,"name" => "Guadalupe", "activo" => true,],
            ["id" => 257, "state_id" => 8,"name" => "Guadalupe y Calvo", "activo" => true,],
            ["id" => 258, "state_id" => 8,"name" => "Guazapares", "activo" => true,],
            ["id" => 259, "state_id" => 8,"name" => "Guerrero", "activo" => true,],
            ["id" => 260, "state_id" => 8,"name" => "Hidalgo del Parral", "activo" => true,],
            ["id" => 261, "state_id" => 8,"name" => "Huejotitán", "activo" => true,],
            ["id" => 262, "state_id" => 8,"name" => "Ignacio Zaragoza", "activo" => true,],
            ["id" => 263, "state_id" => 8,"name" => "Janos", "activo" => true,],
            ["id" => 264, "state_id" => 8,"name" => "Jiménez", "activo" => true,],
            ["id" => 265, "state_id" => 8,"name" => "Juárez", "activo" => true,],
            ["id" => 266, "state_id" => 8,"name" => "Julimes", "activo" => true,],
            ["id" => 267, "state_id" => 8,"name" => "La Cruz", "activo" => true,],
            ["id" => 268, "state_id" => 8,"name" => "López", "activo" => true,],
            ["id" => 269, "state_id" => 8,"name" => "Madera", "activo" => true,],
            ["id" => 270, "state_id" => 8,"name" => "Maguarichi", "activo" => true,],
            ["id" => 271, "state_id" => 8,"name" => "Manuel Benavides", "activo" => true,],
            ["id" => 272, "state_id" => 8,"name" => "Matachí", "activo" => true,],
            ["id" => 273, "state_id" => 8,"name" => "Matamoros", "activo" => true,],
            ["id" => 274, "state_id" => 8,"name" => "Meoqui", "activo" => true,],
            ["id" => 275, "state_id" => 8,"name" => "Morelos", "activo" => true,],
            ["id" => 276, "state_id" => 8,"name" => "Moris", "activo" => true,],
            ["id" => 277, "state_id" => 8,"name" => "Namiquipa", "activo" => true,],
            ["id" => 278, "state_id" => 8,"name" => "Nonoava", "activo" => true,],
            ["id" => 279, "state_id" => 8,"name" => "Nuevo Casas Grandes", "activo" => true,],
            ["id" => 280, "state_id" => 8,"name" => "Ocampo", "activo" => true,],
            ["id" => 281, "state_id" => 8,"name" => "Ojinaga", "activo" => true,],
            ["id" => 282, "state_id" => 8,"name" => "Praxedis G. Guerrero", "activo" => true,],
            ["id" => 283, "state_id" => 8,"name" => "Riva Palacio", "activo" => true,],
            ["id" => 284, "state_id" => 8,"name" => "Rosales", "activo" => true,],
            ["id" => 285, "state_id" => 8,"name" => "Rosario", "activo" => true,],
            ["id" => 286, "state_id" => 8,"name" => "San Francisco de Borja", "activo" => true,],
            ["id" => 287, "state_id" => 8,"name" => "San Francisco de Conchos", "activo" => true,],
            ["id" => 288, "state_id" => 8,"name" => "San Francisco del Oro", "activo" => true,],
            ["id" => 289, "state_id" => 8,"name" => "Santa Bárbara", "activo" => true,],
            ["id" => 290, "state_id" => 8,"name" => "Santa Isabel", "activo" => true,],
            ["id" => 291, "state_id" => 8,"name" => "Satevó", "activo" => true,],
            ["id" => 292, "state_id" => 8,"name" => "Saucillo", "activo" => true,],
            ["id" => 293, "state_id" => 8,"name" => "Temósachi", "activo" => true,],
            ["id" => 294, "state_id" => 8,"name" => "Urique", "activo" => true,],
            ["id" => 295, "state_id" => 8,"name" => "Uruachi", "activo" => true,],
            ["id" => 296, "state_id" => 8,"name" => "Valle de Zaragoza", "activo" => true,],
            ["id" => 297, "state_id" => 9,"name" => "Alvaro Obregón", "activo" => true,],
            ["id" => 298, "state_id" => 9,"name" => "Azcapotzalco", "activo" => true,],
            ["id" => 299, "state_id" => 9,"name" => "Benito Juárez", "activo" => true,],
            ["id" => 300, "state_id" => 9,"name" => "Coyoacán", "activo" => true,],
            ["id" => 301, "state_id" => 9,"name" => "Cuajimalpa de Morelos", "activo" => true,],
            ["id" => 302, "state_id" => 9,"name" => "Cuauhtémoc", "activo" => true,],
            ["id" => 303, "state_id" => 9,"name" => "Gustavo A. Madero", "activo" => true,],
            ["id" => 304, "state_id" => 9,"name" => "Iztacalco", "activo" => true,],
            ["id" => 305, "state_id" => 9,"name" => "Iztapalapa", "activo" => true,],
            ["id" => 306, "state_id" => 9,"name" => "La Magdalena Contreras", "activo" => true,],
            ["id" => 307, "state_id" => 9,"name" => "Miguel Hidalgo", "activo" => true,],
            ["id" => 308, "state_id" => 9,"name" => "Milpa Alta", "activo" => true,],
            ["id" => 309, "state_id" => 9,"name" => "Tláhuac", "activo" => true,],
            ["id" => 310, "state_id" => 9,"name" => "Tlalpan", "activo" => true,],
            ["id" => 311, "state_id" => 9,"name" => "Venustiano Carranza", "activo" => true,],
            ["id" => 312, "state_id" => 9,"name" => "Xochimilco", "activo" => true,],
            ["id" => 313, "state_id" => 10,"name" => "Canatlán", "activo" => true,],
            ["id" => 314, "state_id" => 10,"name" => "Canelas", "activo" => true,],
            ["id" => 315, "state_id" => 10,"name" => "Coneto de Comonfort", "activo" => true,],
            ["id" => 316, "state_id" => 10,"name" => "Cuencamé", "activo" => true,],
            ["id" => 317, "state_id" => 10,"name" => "Durango", "activo" => true,],
            ["id" => 318, "state_id" => 10,"name" => "El Oro", "activo" => true,],
            ["id" => 319, "state_id" => 10,"name" => "Gómez Palacio", "activo" => true,],
            ["id" => 320, "state_id" => 10,"name" => "Gral. Simón Boívar", "activo" => true,],
            ["id" => 321, "state_id" => 10,"name" => "Guadalupe Victoria", "activo" => true,],
            ["id" => 322, "state_id" => 10,"name" => "Guanaceví", "activo" => true,],
            ["id" => 323, "state_id" => 10,"name" => "Hidalgo", "activo" => true,],
            ["id" => 324, "state_id" => 10,"name" => "Indé", "activo" => true,],
            ["id" => 325, "state_id" => 10,"name" => "Lerdo", "activo" => true,],
            ["id" => 326, "state_id" => 10,"name" => "Mapimí", "activo" => true,],
            ["id" => 327, "state_id" => 10,"name" => "Mezquital", "activo" => true,],
            ["id" => 328, "state_id" => 10,"name" => "Nazas", "activo" => true,],
            ["id" => 329, "state_id" => 10,"name" => "name de Dios", "activo" => true,],
            ["id" => 330, "state_id" => 10,"name" => "Nuevo Ideal", "activo" => true,],
            ["id" => 331, "state_id" => 10,"name" => "Ocampo", "activo" => true,],
            ["id" => 332, "state_id" => 10,"name" => "Otáez", "activo" => true,],
            ["id" => 333, "state_id" => 10,"name" => "Pánuco de Coronado", "activo" => true,],
            ["id" => 334, "state_id" => 10,"name" => "Peñón Blanco", "activo" => true,],
            ["id" => 335, "state_id" => 10,"name" => "Poanas", "activo" => true,],
            ["id" => 336, "state_id" => 10,"name" => "Pueblo Nuevo", "activo" => true,],
            ["id" => 337, "state_id" => 10,"name" => "Rodeo", "activo" => true,],
            ["id" => 338, "state_id" => 10,"name" => "San Bernardo", "activo" => true,],
            ["id" => 339, "state_id" => 10,"name" => "San Dimas", "activo" => true,],
            ["id" => 340, "state_id" => 10,"name" => "San Juan de Guadalupe", "activo" => true,],
            ["id" => 341, "state_id" => 10,"name" => "San Juan del Río", "activo" => true,],
            ["id" => 342, "state_id" => 10,"name" => "San Luis del Co", "activo" => true,],
            ["id" => 343, "state_id" => 10,"name" => "San Pedro del Gallo", "activo" => true,],
            ["id" => 344, "state_id" => 10,"name" => "Santa Clara", "activo" => true,],
            ["id" => 345, "state_id" => 10,"name" => "Santiago Papasquiaro", "activo" => true,],
            ["id" => 346, "state_id" => 10,"name" => "Súchil", "activo" => true,],
            ["id" => 347, "state_id" => 10,"name" => "Tamazula", "activo" => true,],
            ["id" => 348, "state_id" => 10,"name" => "Tepehuanes", "activo" => true,],
            ["id" => 349, "state_id" => 10,"name" => "Tlahualilo", "activo" => true,],
            ["id" => 350, "state_id" => 10,"name" => "Topia", "activo" => true,],
            ["id" => 351, "state_id" => 10,"name" => "Vicente Guerrero", "activo" => true,],
            ["id" => 352, "state_id" => 11,"name" => "Abasolo", "activo" => true,],
            ["id" => 353, "state_id" => 11,"name" => "Acámbaro", "activo" => true,],
            ["id" => 354, "state_id" => 11,"name" => "Allende", "activo" => true,],
            ["id" => 355, "state_id" => 11,"name" => "Apaseo el Alto", "activo" => true,],
            ["id" => 356, "state_id" => 11,"name" => "Apaseo el Grande", "activo" => true,],
            ["id" => 357, "state_id" => 11,"name" => "Atarjea", "activo" => true,],
            ["id" => 358, "state_id" => 11,"name" => "Celaya", "activo" => true,],
            ["id" => 359, "state_id" => 11,"name" => "Comonfort", "activo" => true,],
            ["id" => 360, "state_id" => 11,"name" => "Coroneo", "activo" => true,],
            ["id" => 361, "state_id" => 11,"name" => "Cortazar", "activo" => true,],
            ["id" => 362, "state_id" => 11,"name" => "Cuerámaro", "activo" => true,],
            ["id" => 363, "state_id" => 11,"name" => "Doctor Mora", "activo" => true,],
            ["id" => 364, "state_id" => 11,"name" => "Dolores Hidalgo", "activo" => true,],
            ["id" => 365, "state_id" => 11,"name" => "Guanajuato", "activo" => true,],
            ["id" => 366, "state_id" => 11,"name" => "Huanímaro", "activo" => true,],
            ["id" => 367, "state_id" => 11,"name" => "Irapuato", "activo" => true,],
            ["id" => 368, "state_id" => 11,"name" => "Jaral del Progreso", "activo" => true,],
            ["id" => 369, "state_id" => 11,"name" => "Jerécuaro", "activo" => true,],
            ["id" => 370, "state_id" => 11,"name" => "León", "activo" => true,],
            ["id" => 371, "state_id" => 11,"name" => "Manuel Doblado", "activo" => true,],
            ["id" => 372, "state_id" => 11,"name" => "Moroleón", "activo" => true,],
            ["id" => 373, "state_id" => 11,"name" => "Ocampo", "activo" => true,],
            ["id" => 374, "state_id" => 11,"name" => "Pénjamo", "activo" => true,],
            ["id" => 375, "state_id" => 11,"name" => "Pueblo Nuevo", "activo" => true,],
            ["id" => 376, "state_id" => 11,"name" => "Purísima del Rincón", "activo" => true,],
            ["id" => 377, "state_id" => 11,"name" => "Romita", "activo" => true,],
            ["id" => 378, "state_id" => 11,"name" => "Salamanca", "activo" => true,],
            ["id" => 379, "state_id" => 11,"name" => "Salvatierra", "activo" => true,],
            ["id" => 380, "state_id" => 11,"name" => "San Diego de la Unión", "activo" => true,],
            ["id" => 381, "state_id" => 11,"name" => "San Felipe", "activo" => true,],
            ["id" => 382, "state_id" => 11,"name" => "San Francisco del Rincón", "activo" => true,],
            ["id" => 383, "state_id" => 11,"name" => "San José Iturbide", "activo" => true,],
            ["id" => 384, "state_id" => 11,"name" => "San Luis de la Paz", "activo" => true,],
            ["id" => 385, "state_id" => 11,"name" => "Santa Catarina", "activo" => true,],
            ["id" => 386, "state_id" => 11,"name" => "Santa Cruz de Juventino Rosas", "activo" => true,],
            ["id" => 387, "state_id" => 11,"name" => "Santiago Maravatío", "activo" => true,],
            ["id" => 388, "state_id" => 11,"name" => "Silao", "activo" => true,],
            ["id" => 389, "state_id" => 11,"name" => "Tarandacuao", "activo" => true,],
            ["id" => 390, "state_id" => 11,"name" => "Tarimoro", "activo" => true,],
            ["id" => 391, "state_id" => 11,"name" => "Tierra Blanca", "activo" => true,],
            ["id" => 392, "state_id" => 11,"name" => "Uriangato", "activo" => true,],
            ["id" => 393, "state_id" => 11,"name" => "Valle de Santiago", "activo" => true,],
            ["id" => 394, "state_id" => 11,"name" => "Victoria", "activo" => true,],
            ["id" => 395, "state_id" => 11,"name" => "Villagrán", "activo" => true,],
            ["id" => 396, "state_id" => 11,"name" => "Xichú", "activo" => true,],
            ["id" => 397, "state_id" => 11,"name" => "Yuriria", "activo" => true,],
            ["id" => 398, "state_id" => 12,"name" => "Acapulco de Juárez", "activo" => true,],
            ["id" => 399, "state_id" => 12,"name" => "Acatepec", "activo" => true,],
            ["id" => 400, "state_id" => 12,"name" => "Ahuacuotzingo", "activo" => true,],
            ["id" => 401, "state_id" => 12,"name" => "Ajuchitlán del Progreso", "activo" => true,],
            ["id" => 402, "state_id" => 12,"name" => "Alcozauca de Guerrero", "activo" => true,],
            ["id" => 403, "state_id" => 12,"name" => "Alpoyeca", "activo" => true,],
            ["id" => 404, "state_id" => 12,"name" => "Apaxtla", "activo" => true,],
            ["id" => 405, "state_id" => 12,"name" => "Arcelia", "activo" => true,],
            ["id" => 406, "state_id" => 12,"name" => "Atenango del Río", "activo" => true,],
            ["id" => 407, "state_id" => 12,"name" => "Atlamajalcingo del Monte", "activo" => true,],
            ["id" => 408, "state_id" => 12,"name" => "Atlixtac", "activo" => true,],
            ["id" => 409, "state_id" => 12,"name" => "Atoyac de Álvarez", "activo" => true,],
            ["id" => 410, "state_id" => 12,"name" => "Ayutla de los Libres", "activo" => true,],
            ["id" => 411, "state_id" => 12,"name" => "Azoyú", "activo" => true,],
            ["id" => 412, "state_id" => 12,"name" => "Benito Juárez", "activo" => true,],
            ["id" => 413, "state_id" => 12,"name" => "Buenavista de Cuéllar", "activo" => true,],
            ["id" => 414, "state_id" => 12,"name" => "Chilapa de Alvarez", "activo" => true,],
            ["id" => 415, "state_id" => 12,"name" => "Chilpancingo de los Bravo", "activo" => true,],
            ["id" => 416, "state_id" => 12,"name" => "Coahuayutla de José María Izazaga", "activo" => true,],
            ["id" => 417, "state_id" => 12,"name" => "Cochoapa el Grande", "activo" => true,],
            ["id" => 418, "state_id" => 12,"name" => "Cocula", "activo" => true,],
            ["id" => 419, "state_id" => 12,"name" => "Copala", "activo" => true,],
            ["id" => 420, "state_id" => 12,"name" => "Copalillo", "activo" => true,],
            ["id" => 421, "state_id" => 12,"name" => "Copanatoyac", "activo" => true,],
            ["id" => 422, "state_id" => 12,"name" => "Coyuca de Benítez", "activo" => true,],
            ["id" => 423, "state_id" => 12,"name" => "Coyuca de Catalán", "activo" => true,],
            ["id" => 424, "state_id" => 12,"name" => "Cuajinicuilapa", "activo" => true,],
            ["id" => 425, "state_id" => 12,"name" => "Cualác", "activo" => true,],
            ["id" => 426, "state_id" => 12,"name" => "Cuautepec", "activo" => true,],
            ["id" => 427, "state_id" => 12,"name" => "Cuetzala del Progreso", "activo" => true,],
            ["id" => 428, "state_id" => 12,"name" => "Cutzamala de Pinzón", "activo" => true,],
            ["id" => 429, "state_id" => 12,"name" => "Eduardo Neri", "activo" => true,],
            ["id" => 430, "state_id" => 12,"name" => "Florencio Villarreal", "activo" => true,],
            ["id" => 431, "state_id" => 12,"name" => "General Canuto A. Neri", "activo" => true,],
            ["id" => 432, "state_id" => 12,"name" => "General Heliodoro Castillo", "activo" => true,],
            ["id" => 433, "state_id" => 12,"name" => "Huamuxtitlán", "activo" => true,],
            ["id" => 434, "state_id" => 12,"name" => "Huitzuco de los Figueroa", "activo" => true,],
            ["id" => 435, "state_id" => 12,"name" => "Iguala de la Independencia", "activo" => true,],
            ["id" => 436, "state_id" => 12,"name" => "Igualapa", "activo" => true,],
            ["id" => 437, "state_id" => 12,"name" => "Ixcateopan de Cuauhtémoc", "activo" => true,],
            ["id" => 438, "state_id" => 12,"name" => "José Azueta", "activo" => true,],
            ["id" => 439, "state_id" => 12,"name" => "José Joaquin de Herrera", "activo" => true,],
            ["id" => 440, "state_id" => 12,"name" => "Juan R. Escudero", "activo" => true,],
            ["id" => 441, "state_id" => 12,"name" => "La Unión de Isidoro Montes de Oca", "activo" => true,],
            ["id" => 442, "state_id" => 12,"name" => "Leonardo Bravo", "activo" => true,],
            ["id" => 443, "state_id" => 12,"name" => "Malinaltepec", "activo" => true,],
            ["id" => 444, "state_id" => 12,"name" => "Marquelia", "activo" => true,],
            ["id" => 445, "state_id" => 12,"name" => "Mártir de Cuilapan", "activo" => true,],
            ["id" => 446, "state_id" => 12,"name" => "Metlatónoc", "activo" => true,],
            ["id" => 447, "state_id" => 12,"name" => "Mochitlán", "activo" => true,],
            ["id" => 448, "state_id" => 12,"name" => "Olinalá", "activo" => true,],
            ["id" => 449, "state_id" => 12,"name" => "Ometepec", "activo" => true,],
            ["id" => 450, "state_id" => 12,"name" => "Pedro Ascencio Alquisiras", "activo" => true,],
            ["id" => 451, "state_id" => 12,"name" => "Petatlán", "activo" => true,],
            ["id" => 452, "state_id" => 12,"name" => "Pilcaya", "activo" => true,],
            ["id" => 453, "state_id" => 12,"name" => "Pungarabato", "activo" => true,],
            ["id" => 454, "state_id" => 12,"name" => "Quechultenango", "activo" => true,],
            ["id" => 455, "state_id" => 12,"name" => "San Luis Acatlán", "activo" => true,],
            ["id" => 456, "state_id" => 12,"name" => "San Marcos", "activo" => true,],
            ["id" => 457, "state_id" => 12,"name" => "San Miguel Totolapan", "activo" => true,],
            ["id" => 458, "state_id" => 12,"name" => "Taxco de Alarcón", "activo" => true,],
            ["id" => 459, "state_id" => 12,"name" => "Tecoanapa", "activo" => true,],
            ["id" => 460, "state_id" => 12,"name" => "Técpan de Galeana", "activo" => true,],
            ["id" => 461, "state_id" => 12,"name" => "Teloloapan", "activo" => true,],
            ["id" => 462, "state_id" => 12,"name" => "Tepecoacuilco de Trujano", "activo" => true,],
            ["id" => 463, "state_id" => 12,"name" => "Tetipac", "activo" => true,],
            ["id" => 464, "state_id" => 12,"name" => "Tixtla de Guerrero", "activo" => true,],
            ["id" => 465, "state_id" => 12,"name" => "Tlacoachistlahuaca", "activo" => true,],
            ["id" => 466, "state_id" => 12,"name" => "Tlacoapa", "activo" => true,],
            ["id" => 467, "state_id" => 12,"name" => "Tlalchapa", "activo" => true,],
            ["id" => 468, "state_id" => 12,"name" => "Tlalixtaquilla de Maldonado", "activo" => true,],
            ["id" => 469, "state_id" => 12,"name" => "Tlapa de Comonfort", "activo" => true,],
            ["id" => 470, "state_id" => 12,"name" => "Tlapehuala", "activo" => true,],
            ["id" => 471, "state_id" => 12,"name" => "Xalpatláhuac", "activo" => true,],
            ["id" => 472, "state_id" => 12,"name" => "Xochihuehuetlán", "activo" => true,],
            ["id" => 473, "state_id" => 12,"name" => "Xochistlahuaca", "activo" => true,],
            ["id" => 474, "state_id" => 12,"name" => "Zapotitlán Tablas", "activo" => true,],
            ["id" => 475, "state_id" => 12,"name" => "Zirándaro", "activo" => true,],
            ["id" => 476, "state_id" => 12,"name" => "Zitlala", "activo" => true,],
            ["id" => 477, "state_id" => 13,"name" => "Acatlán", "activo" => true,],
            ["id" => 478, "state_id" => 13,"name" => "Acaxochitlán", "activo" => true,],
            ["id" => 479, "state_id" => 13,"name" => "Actopan", "activo" => true,],
            ["id" => 480, "state_id" => 13,"name" => "Agua Blanca de Iturbide", "activo" => true,],
            ["id" => 481, "state_id" => 13,"name" => "Ajacuba", "activo" => true,],
            ["id" => 482, "state_id" => 13,"name" => "Alfajayucan", "activo" => true,],
            ["id" => 483, "state_id" => 13,"name" => "Almoloya", "activo" => true,],
            ["id" => 484, "state_id" => 13,"name" => "Apan", "activo" => true,],
            ["id" => 485, "state_id" => 13,"name" => "Atitalaquia", "activo" => true,],
            ["id" => 486, "state_id" => 13,"name" => "Atlapexco", "activo" => true,],
            ["id" => 487, "state_id" => 13,"name" => "Atotonilco de Tula", "activo" => true,],
            ["id" => 488, "state_id" => 13,"name" => "Atotonilco el Grande", "activo" => true,],
            ["id" => 489, "state_id" => 13,"name" => "Calnali", "activo" => true,],
            ["id" => 490, "state_id" => 13,"name" => "Cardonal", "activo" => true,],
            ["id" => 491, "state_id" => 13,"name" => "Chapantongo", "activo" => true,],
            ["id" => 492, "state_id" => 13,"name" => "Chapulhuacán", "activo" => true,],
            ["id" => 493, "state_id" => 13,"name" => "Chilcuautla", "activo" => true,],
            ["id" => 494, "state_id" => 13,"name" => "Cuautepec de Hinojosa", "activo" => true,],
            ["id" => 495, "state_id" => 13,"name" => "El Arenal", "activo" => true,],
            ["id" => 496, "state_id" => 13,"name" => "Eloxochitlán", "activo" => true,],
            ["id" => 497, "state_id" => 13,"name" => "Emiliano Zapata", "activo" => true,],
            ["id" => 498, "state_id" => 13,"name" => "Epazoyucan", "activo" => true,],
            ["id" => 499, "state_id" => 13,"name" => "Francisco I. Madero", "activo" => true,],
            ["id" => 500, "state_id" => 13,"name" => "Huasca de Ocampo", "activo" => true,],
            ["id" => 501, "state_id" => 13,"name" => "Huautla", "activo" => true,],
            ["id" => 502, "state_id" => 13,"name" => "Huazalingo", "activo" => true,],
            ["id" => 503, "state_id" => 13,"name" => "Huehuetla", "activo" => true,],
            ["id" => 504, "state_id" => 13,"name" => "Huejutla de Reyes", "activo" => true,],
            ["id" => 505, "state_id" => 13,"name" => "Huichapan", "activo" => true,],
            ["id" => 506, "state_id" => 13,"name" => "Ixmiquilpan", "activo" => true,],
            ["id" => 507, "state_id" => 13,"name" => "Jacala de Ledezma", "activo" => true,],
            ["id" => 508, "state_id" => 13,"name" => "Jaltocán", "activo" => true,],
            ["id" => 509, "state_id" => 13,"name" => "Juárez Hidalgo", "activo" => true,],
            ["id" => 510, "state_id" => 13,"name" => "La Misión", "activo" => true,],
            ["id" => 511, "state_id" => 13,"name" => "Lolotla", "activo" => true,],
            ["id" => 512, "state_id" => 13,"name" => "Metepec", "activo" => true,],
            ["id" => 513, "state_id" => 13,"name" => "Metztitlán", "activo" => true,],
            ["id" => 514, "state_id" => 13,"name" => "Mineral de la Reforma", "activo" => true,],
            ["id" => 515, "state_id" => 13,"name" => "Mineral del Chico", "activo" => true,],
            ["id" => 516, "state_id" => 13,"name" => "Mineral del Monte", "activo" => true,],
            ["id" => 517, "state_id" => 13,"name" => "Mixquiahuala de Juárez", "activo" => true,],
            ["id" => 518, "state_id" => 13,"name" => "Molango de Escamilla", "activo" => true,],
            ["id" => 519, "state_id" => 13,"name" => "Nicolás Flores", "activo" => true,],
            ["id" => 520, "state_id" => 13,"name" => "Nopala de Villagrán", "activo" => true,],
            ["id" => 521, "state_id" => 13,"name" => "Omitlán de Juárez", "activo" => true,],
            ["id" => 522, "state_id" => 13,"name" => "Pachuca de Soto", "activo" => true,],
            ["id" => 523, "state_id" => 13,"name" => "Pacula", "activo" => true,],
            ["id" => 524, "state_id" => 13,"name" => "Pisaflores", "activo" => true,],
            ["id" => 525, "state_id" => 13,"name" => "Progreso de Obregón", "activo" => true,],
            ["id" => 526, "state_id" => 13,"name" => "San Agustín Metzquititlán", "activo" => true,],
            ["id" => 527, "state_id" => 13,"name" => "San Agustín Tlaxiaca", "activo" => true,],
            ["id" => 528, "state_id" => 13,"name" => "San Bartolo Tutotepec", "activo" => true,],
            ["id" => 529, "state_id" => 13,"name" => "San Felipe Orizatlán", "activo" => true,],
            ["id" => 530, "state_id" => 13,"name" => "San Salvador", "activo" => true,],
            ["id" => 531, "state_id" => 13,"name" => "Santiago de Anaya", "activo" => true,],
            ["id" => 532, "state_id" => 13,"name" => "Santiago Tulantepec de Lugo Guerrero", "activo" => true,],
            ["id" => 533, "state_id" => 13,"name" => "Singuilucan", "activo" => true,],
            ["id" => 534, "state_id" => 13,"name" => "Tasquillo", "activo" => true,],
            ["id" => 535, "state_id" => 13,"name" => "Tecozautla", "activo" => true,],
            ["id" => 536, "state_id" => 13,"name" => "Tenango de Doria", "activo" => true,],
            ["id" => 537, "state_id" => 13,"name" => "Tepeapulco", "activo" => true,],
            ["id" => 538, "state_id" => 13,"name" => "Tepehuacán de Guerrero", "activo" => true,],
            ["id" => 539, "state_id" => 13,"name" => "Tepeji del Río de Ocampo", "activo" => true,],
            ["id" => 540, "state_id" => 13,"name" => "Tepetitlán", "activo" => true,],
            ["id" => 541, "state_id" => 13,"name" => "Tetepango", "activo" => true,],
            ["id" => 542, "state_id" => 13,"name" => "Tezontepec de Aldama", "activo" => true,],
            ["id" => 543, "state_id" => 13,"name" => "Tianguistengo", "activo" => true,],
            ["id" => 544, "state_id" => 13,"name" => "Tizayuca", "activo" => true,],
            ["id" => 545, "state_id" => 13,"name" => "Tlahuelilpan", "activo" => true,],
            ["id" => 546, "state_id" => 13,"name" => "Tlahuiltepa", "activo" => true,],
            ["id" => 547, "state_id" => 13,"name" => "Tlanalapa", "activo" => true,],
            ["id" => 548, "state_id" => 13,"name" => "Tlanchinol", "activo" => true,],
            ["id" => 549, "state_id" => 13,"name" => "Tlaxcoapan", "activo" => true,],
            ["id" => 550, "state_id" => 13,"name" => "Tolcayuca", "activo" => true,],
            ["id" => 551, "state_id" => 13,"name" => "Tula de Allende", "activo" => true,],
            ["id" => 552, "state_id" => 13,"name" => "Tulancingo de Bravo", "activo" => true,],
            ["id" => 553, "state_id" => 13,"name" => "Villa de Tezontepec", "activo" => true,],
            ["id" => 554, "state_id" => 13,"name" => "Xochiatipan", "activo" => true,],
            ["id" => 555, "state_id" => 13,"name" => "Xochicoatlán", "activo" => true,],
            ["id" => 556, "state_id" => 13,"name" => "Yahualica", "activo" => true,],
            ["id" => 557, "state_id" => 13,"name" => "Zacualtipán de Ángeles", "activo" => true,],
            ["id" => 558, "state_id" => 13,"name" => "Zapotlán de Juárez", "activo" => true,],
            ["id" => 559, "state_id" => 13,"name" => "Zempoala", "activo" => true,],
            ["id" => 560, "state_id" => 13,"name" => "Zimapán", "activo" => true,],
            ["id" => 561, "state_id" => 14,"name" => "Acatic", "activo" => true,],
            ["id" => 562, "state_id" => 14,"name" => "Acatlán de Juárez", "activo" => true,],
            ["id" => 563, "state_id" => 14,"name" => "Ahualulco de Mercado", "activo" => true,],
            ["id" => 564, "state_id" => 14,"name" => "Amacueca", "activo" => true,],
            ["id" => 565, "state_id" => 14,"name" => "Amatitán", "activo" => true,],
            ["id" => 566, "state_id" => 14,"name" => "Ameca", "activo" => true,],
            ["id" => 567, "state_id" => 14,"name" => "Arandas", "activo" => true,],
            ["id" => 568, "state_id" => 14,"name" => "Atemajac de Brizuela", "activo" => true,],
            ["id" => 569, "state_id" => 14,"name" => "Atengo", "activo" => true,],
            ["id" => 570, "state_id" => 14,"name" => "Atenguillo", "activo" => true,],
            ["id" => 571, "state_id" => 14,"name" => "Atotonilco el Alto", "activo" => true,],
            ["id" => 572, "state_id" => 14,"name" => "Atoyac", "activo" => true,],
            ["id" => 573, "state_id" => 14,"name" => "Autlán de Navarro", "activo" => true,],
            ["id" => 574, "state_id" => 14,"name" => "Ayotlán", "activo" => true,],
            ["id" => 575, "state_id" => 14,"name" => "Ayutla", "activo" => true,],
            ["id" => 576, "state_id" => 14,"name" => "Bolaños", "activo" => true,],
            ["id" => 577, "state_id" => 14,"name" => "Cabo Corrientes", "activo" => true,],
            ["id" => 578, "state_id" => 14,"name" => "Cañadas de Obregón", "activo" => true,],
            ["id" => 579, "state_id" => 14,"name" => "Casimiro Castillo", "activo" => true,],
            ["id" => 580, "state_id" => 14,"name" => "Chapala", "activo" => true,],
            ["id" => 581, "state_id" => 14,"name" => "Chimaltitán", "activo" => true,],
            ["id" => 582, "state_id" => 14,"name" => "Chiquilistlán", "activo" => true,],
            ["id" => 583, "state_id" => 14,"name" => "Cihuatlán", "activo" => true,],
            ["id" => 584, "state_id" => 14,"name" => "Cocula", "activo" => true,],
            ["id" => 585, "state_id" => 14,"name" => "Colotlán", "activo" => true,],
            ["id" => 586, "state_id" => 14,"name" => "Concepción de Buenos Aires", "activo" => true,],
            ["id" => 587, "state_id" => 14,"name" => "Cuautitlán de García Barragán", "activo" => true,],
            ["id" => 588, "state_id" => 14,"name" => "Cuautla", "activo" => true,],
            ["id" => 589, "state_id" => 14,"name" => "Cuquío", "activo" => true,],
            ["id" => 590, "state_id" => 14,"name" => "Degollado", "activo" => true,],
            ["id" => 591, "state_id" => 14,"name" => "Ejutla", "activo" => true,],
            ["id" => 592, "state_id" => 14,"name" => "EL Arenal", "activo" => true,],
            ["id" => 593, "state_id" => 14,"name" => "El Grullo", "activo" => true,],
            ["id" => 594, "state_id" => 14,"name" => "El Limón", "activo" => true,],
            ["id" => 595, "state_id" => 14,"name" => "El Salto", "activo" => true,],
            ["id" => 596, "state_id" => 14,"name" => "Encarnación de Díaz", "activo" => true,],
            ["id" => 597, "state_id" => 14,"name" => "Etzatlán", "activo" => true,],
            ["id" => 598, "state_id" => 14,"name" => "Gómez Farías", "activo" => true,],
            ["id" => 599, "state_id" => 14,"name" => "Guachinango", "activo" => true,],
            ["id" => 600, "state_id" => 14,"name" => "Guadalajara", "activo" => true,],
            ["id" => 601, "state_id" => 14,"name" => "Hostotipaquillo", "activo" => true,],
            ["id" => 602, "state_id" => 14,"name" => "Huejúcar", "activo" => true,],
            ["id" => 603, "state_id" => 14,"name" => "Huejuquilla el Alto", "activo" => true,],
            ["id" => 604, "state_id" => 14,"name" => "Ixtlahuacán de los Membrillos", "activo" => true,],
            ["id" => 605, "state_id" => 14,"name" => "Ixtlahuacán del Río", "activo" => true,],
            ["id" => 606, "state_id" => 14,"name" => "Jalostotitlán", "activo" => true,],
            ["id" => 607, "state_id" => 14,"name" => "Jamay", "activo" => true,],
            ["id" => 608, "state_id" => 14,"name" => "Jesús María", "activo" => true,],
            ["id" => 609, "state_id" => 14,"name" => "Jilotlán de los Dolores", "activo" => true,],
            ["id" => 610, "state_id" => 14,"name" => "Jocotepec", "activo" => true,],
            ["id" => 611, "state_id" => 14,"name" => "Juanacatlán", "activo" => true,],
            ["id" => 612, "state_id" => 14,"name" => "Juchitlán", "activo" => true,],
            ["id" => 613, "state_id" => 14,"name" => "La Barca", "activo" => true,],
            ["id" => 614, "state_id" => 14,"name" => "La Huerta", "activo" => true,],
            ["id" => 615, "state_id" => 14,"name" => "La Manzanilla de la Paz", "activo" => true,],
            ["id" => 616, "state_id" => 14,"name" => "Lagos de Moreno", "activo" => true,],
            ["id" => 617, "state_id" => 14,"name" => "Magdalena", "activo" => true,],
            ["id" => 618, "state_id" => 14,"name" => "Mascota", "activo" => true,],
            ["id" => 619, "state_id" => 14,"name" => "Mazamitla", "activo" => true,],
            ["id" => 620, "state_id" => 14,"name" => "Mexticacán", "activo" => true,],
            ["id" => 621, "state_id" => 14,"name" => "Mezquitic", "activo" => true,],
            ["id" => 622, "state_id" => 14,"name" => "Mixtlán", "activo" => true,],
            ["id" => 623, "state_id" => 14,"name" => "Ocotlán", "activo" => true,],
            ["id" => 624, "state_id" => 14,"name" => "Ojuelos de Jalisco", "activo" => true,],
            ["id" => 625, "state_id" => 14,"name" => "Pihuamo", "activo" => true,],
            ["id" => 626, "state_id" => 14,"name" => "Poncitlán", "activo" => true,],
            ["id" => 627, "state_id" => 14,"name" => "Puerto Vallarta", "activo" => true,],
            ["id" => 628, "state_id" => 14,"name" => "Quitupan", "activo" => true,],
            ["id" => 629, "state_id" => 14,"name" => "San Cristóbal de la Barranca", "activo" => true,],
            ["id" => 630, "state_id" => 14,"name" => "San Diego de Alejandría", "activo" => true,],
            ["id" => 631, "state_id" => 14,"name" => "San Gabriel", "activo" => true,],
            ["id" => 632, "state_id" => 14,"name" => "San Juan de los Lagos", "activo" => true,],
            ["id" => 633, "state_id" => 14,"name" => "San Juanito de Escobedo", "activo" => true,],
            ["id" => 634, "state_id" => 14,"name" => "San Julián", "activo" => true,],
            ["id" => 635, "state_id" => 14,"name" => "San Marcos", "activo" => true,],
            ["id" => 636, "state_id" => 14,"name" => "San Martín de Bolaños", "activo" => true,],
            ["id" => 637, "state_id" => 14,"name" => "San Martín Hidalgo", "activo" => true,],
            ["id" => 638, "state_id" => 14,"name" => "San Miguel el Alto", "activo" => true,],
            ["id" => 639, "state_id" => 14,"name" => "San Sebastián del Oeste", "activo" => true,],
            ["id" => 640, "state_id" => 14,"name" => "Santa María de los Ángeles", "activo" => true,],
            ["id" => 641, "state_id" => 14,"name" => "Santa María del Oro", "activo" => true,],
            ["id" => 642, "state_id" => 14,"name" => "Sayula", "activo" => true,],
            ["id" => 643, "state_id" => 14,"name" => "Tala", "activo" => true,],
            ["id" => 644, "state_id" => 14,"name" => "Talpa de Allende", "activo" => true,],
            ["id" => 645, "state_id" => 14,"name" => "Tamazula de Gordiano", "activo" => true,],
            ["id" => 646, "state_id" => 14,"name" => "Tapalpa", "activo" => true,],
            ["id" => 647, "state_id" => 14,"name" => "Tecalitlán", "activo" => true,],
            ["id" => 648, "state_id" => 14,"name" => "Techaluta de Montenegro", "activo" => true,],
            ["id" => 649, "state_id" => 14,"name" => "Tecolotlán", "activo" => true,],
            ["id" => 650, "state_id" => 14,"name" => "Tenamaxtlán", "activo" => true,],
            ["id" => 651, "state_id" => 14,"name" => "Teocaltiche", "activo" => true,],
            ["id" => 652, "state_id" => 14,"name" => "Teocuitatlán de Corona", "activo" => true,],
            ["id" => 653, "state_id" => 14,"name" => "Tepatitlán de Morelos", "activo" => true,],
            ["id" => 654, "state_id" => 14,"name" => "Tequila", "activo" => true,],
            ["id" => 655, "state_id" => 14,"name" => "Teuchitlán", "activo" => true,],
            ["id" => 656, "state_id" => 14,"name" => "Tizapán el Alto", "activo" => true,],
            ["id" => 657, "state_id" => 14,"name" => "Tlajomulco de Zúñiga", "activo" => true,],
            ["id" => 658, "state_id" => 14,"name" => "Tlaquepaque", "activo" => true,],
            ["id" => 659, "state_id" => 14,"name" => "Tolimán", "activo" => true,],
            ["id" => 660, "state_id" => 14,"name" => "Tomatlán", "activo" => true,],
            ["id" => 661, "state_id" => 14,"name" => "Tonalá", "activo" => true,],
            ["id" => 662, "state_id" => 14,"name" => "Tonaya", "activo" => true,],
            ["id" => 663, "state_id" => 14,"name" => "Tonila", "activo" => true,],
            ["id" => 664, "state_id" => 14,"name" => "Totatiche", "activo" => true,],
            ["id" => 665, "state_id" => 14,"name" => "Tototlán", "activo" => true,],
            ["id" => 666, "state_id" => 14,"name" => "Tuxcacuesco", "activo" => true,],
            ["id" => 667, "state_id" => 14,"name" => "Tuxcueca", "activo" => true,],
            ["id" => 668, "state_id" => 14,"name" => "Tuxpan", "activo" => true,],
            ["id" => 669, "state_id" => 14,"name" => "Unión de San Antonio", "activo" => true,],
            ["id" => 670, "state_id" => 14,"name" => "Unión de Tula", "activo" => true,],
            ["id" => 671, "state_id" => 14,"name" => "Valle de Guadalupe", "activo" => true,],
            ["id" => 672, "state_id" => 14,"name" => "Valle de Juárez", "activo" => true,],
            ["id" => 673, "state_id" => 14,"name" => "Villa Corona", "activo" => true,],
            ["id" => 674, "state_id" => 14,"name" => "Villa Guerrero", "activo" => true,],
            ["id" => 675, "state_id" => 14,"name" => "Villa Hidalgo", "activo" => true,],
            ["id" => 676, "state_id" => 14,"name" => "Villa Purificación", "activo" => true,],
            ["id" => 677, "state_id" => 14,"name" => "Yahualica de González Gallo", "activo" => true,],
            ["id" => 678, "state_id" => 14,"name" => "Zacoalco de Torres", "activo" => true,],
            ["id" => 679, "state_id" => 14,"name" => "Zapopan", "activo" => true,],
            ["id" => 680, "state_id" => 14,"name" => "Zapotiltic", "activo" => true,],
            ["id" => 681, "state_id" => 14,"name" => "Zapotitlán de Vadillo", "activo" => true,],
            ["id" => 682, "state_id" => 14,"name" => "Zapotlán del Rey", "activo" => true,],
            ["id" => 683, "state_id" => 14,"name" => "Zapotlán el Grande", "activo" => true,],
            ["id" => 684, "state_id" => 14,"name" => "Zapotlanejo", "activo" => true,],
            ["id" => 685, "state_id" => 15,"name" => "Acambay", "activo" => true,],
            ["id" => 686, "state_id" => 15,"name" => "Acolman", "activo" => true,],
            ["id" => 687, "state_id" => 15,"name" => "Aculco", "activo" => true,],
            ["id" => 688, "state_id" => 15,"name" => "Almoloya de Alquisiras", "activo" => true,],
            ["id" => 689, "state_id" => 15,"name" => "Almoloya de Juárez", "activo" => true,],
            ["id" => 690, "state_id" => 15,"name" => "Almoloya del Río", "activo" => true,],
            ["id" => 691, "state_id" => 15,"name" => "Amanalco", "activo" => true,],
            ["id" => 692, "state_id" => 15,"name" => "Amatepec", "activo" => true,],
            ["id" => 693, "state_id" => 15,"name" => "Amecameca", "activo" => true,],
            ["id" => 694, "state_id" => 15,"name" => "Apaxco", "activo" => true,],
            ["id" => 695, "state_id" => 15,"name" => "Atenco", "activo" => true,],
            ["id" => 696, "state_id" => 15,"name" => "Atizapán", "activo" => true,],
            ["id" => 697, "state_id" => 15,"name" => "Atizapán de Zaragoza", "activo" => true,],
            ["id" => 698, "state_id" => 15,"name" => "Atlacomulco", "activo" => true,],
            ["id" => 699, "state_id" => 15,"name" => "Atlautla", "activo" => true,],
            ["id" => 700, "state_id" => 15,"name" => "Axapusco", "activo" => true,],
            ["id" => 701, "state_id" => 15,"name" => "Ayapango", "activo" => true,],
            ["id" => 702, "state_id" => 15,"name" => "Calimaya", "activo" => true,],
            ["id" => 703, "state_id" => 15,"name" => "Capulhuac", "activo" => true,],
            ["id" => 704, "state_id" => 15,"name" => "Chalco", "activo" => true,],
            ["id" => 705, "state_id" => 15,"name" => "Chapa de Mota", "activo" => true,],
            ["id" => 706, "state_id" => 15,"name" => "Chapultepec", "activo" => true,],
            ["id" => 707, "state_id" => 15,"name" => "Chiautla", "activo" => true,],
            ["id" => 708, "state_id" => 15,"name" => "Chicoloapan", "activo" => true,],
            ["id" => 709, "state_id" => 15,"name" => "Chiconcuac", "activo" => true,],
            ["id" => 710, "state_id" => 15,"name" => "Chimalhuacán", "activo" => true,],
            ["id" => 711, "state_id" => 15,"name" => "Coacalco de Berriozábal", "activo" => true,],
            ["id" => 712, "state_id" => 15,"name" => "Coatepec Harinas", "activo" => true,],
            ["id" => 713, "state_id" => 15,"name" => "Cocotitlán", "activo" => true,],
            ["id" => 714, "state_id" => 15,"name" => "Coyotepec", "activo" => true,],
            ["id" => 715, "state_id" => 15,"name" => "Cuautitlán", "activo" => true,],
            ["id" => 716, "state_id" => 15,"name" => "Cuautitlán Izcalli", "activo" => true,],
            ["id" => 717, "state_id" => 15,"name" => "Donato Guerra", "activo" => true,],
            ["id" => 718, "state_id" => 15,"name" => "Ecatepec de Morelos", "activo" => true,],
            ["id" => 719, "state_id" => 15,"name" => "Ecatzingo", "activo" => true,],
            ["id" => 720, "state_id" => 15,"name" => "El Oro", "activo" => true,],
            ["id" => 721, "state_id" => 15,"name" => "Huehuetoca", "activo" => true,],
            ["id" => 722, "state_id" => 15,"name" => "Hueypoxtla", "activo" => true,],
            ["id" => 723, "state_id" => 15,"name" => "Huixquilucan", "activo" => true,],
            ["id" => 724, "state_id" => 15,"name" => "Isidro Fabela", "activo" => true,],
            ["id" => 725, "state_id" => 15,"name" => "Ixtapaluca", "activo" => true,],
            ["id" => 726, "state_id" => 15,"name" => "Ixtapan de la Sal", "activo" => true,],
            ["id" => 727, "state_id" => 15,"name" => "Ixtapan del Oro", "activo" => true,],
            ["id" => 728, "state_id" => 15,"name" => "Ixtlahuaca", "activo" => true,],
            ["id" => 729, "state_id" => 15,"name" => "Jaltenco", "activo" => true,],
            ["id" => 730, "state_id" => 15,"name" => "Jilotepec", "activo" => true,],
            ["id" => 731, "state_id" => 15,"name" => "Jilotzingo", "activo" => true,],
            ["id" => 732, "state_id" => 15,"name" => "Jiquipilco", "activo" => true,],
            ["id" => 733, "state_id" => 15,"name" => "Jocotitlán", "activo" => true,],
            ["id" => 734, "state_id" => 15,"name" => "Joquicingo", "activo" => true,],
            ["id" => 735, "state_id" => 15,"name" => "Juchitepec", "activo" => true,],
            ["id" => 736, "state_id" => 15,"name" => "La Paz", "activo" => true,],
            ["id" => 737, "state_id" => 15,"name" => "Lerma", "activo" => true,],
            ["id" => 738, "state_id" => 15,"name" => "Luvianos", "activo" => true,],
            ["id" => 739, "state_id" => 15,"name" => "Malinalco", "activo" => true,],
            ["id" => 740, "state_id" => 15,"name" => "Melchor Ocampo", "activo" => true,],
            ["id" => 741, "state_id" => 15,"name" => "Metepec", "activo" => true,],
            ["id" => 742, "state_id" => 15,"name" => "Mexicaltzingo", "activo" => true,],
            ["id" => 743, "state_id" => 15,"name" => "Morelos", "activo" => true,],
            ["id" => 744, "state_id" => 15,"name" => "Naucalpan de Juárez", "activo" => true,],
            ["id" => 745, "state_id" => 15,"name" => "Nextlalpan", "activo" => true,],
            ["id" => 746, "state_id" => 15,"name" => "Nezahualcóyotl", "activo" => true,],
            ["id" => 747, "state_id" => 15,"name" => "Nicolás Romero", "activo" => true,],
            ["id" => 748, "state_id" => 15,"name" => "Nopaltepec", "activo" => true,],
            ["id" => 749, "state_id" => 15,"name" => "Ocoyoacac", "activo" => true,],
            ["id" => 750, "state_id" => 15,"name" => "Ocuilan", "activo" => true,],
            ["id" => 751, "state_id" => 15,"name" => "Otumba", "activo" => true,],
            ["id" => 752, "state_id" => 15,"name" => "Otzoloapan", "activo" => true,],
            ["id" => 753, "state_id" => 15,"name" => "Otzolotepec", "activo" => true,],
            ["id" => 754, "state_id" => 15,"name" => "Ozumba", "activo" => true,],
            ["id" => 755, "state_id" => 15,"name" => "Papalotla", "activo" => true,],
            ["id" => 756, "state_id" => 15,"name" => "Polotitlán", "activo" => true,],
            ["id" => 757, "state_id" => 15,"name" => "Rayón", "activo" => true,],
            ["id" => 758, "state_id" => 15,"name" => "San Antonio la Isla", "activo" => true,],
            ["id" => 759, "state_id" => 15,"name" => "San Felipe del Progreso", "activo" => true,],
            ["id" => 760, "state_id" => 15,"name" => "San José del Rincón", "activo" => true,],
            ["id" => 761, "state_id" => 15,"name" => "San Martín de las Pirámides", "activo" => true,],
            ["id" => 762, "state_id" => 15,"name" => "San Mateo Atenco", "activo" => true,],
            ["id" => 763, "state_id" => 15,"name" => "San Simón de Guerrero", "activo" => true,],
            ["id" => 764, "state_id" => 15,"name" => "Santo Tomás", "activo" => true,],
            ["id" => 765, "state_id" => 15,"name" => "Soyaniquilpan de Juárez", "activo" => true,],
            ["id" => 766, "state_id" => 15,"name" => "Sultepec", "activo" => true,],
            ["id" => 767, "state_id" => 15,"name" => "Tecámac", "activo" => true,],
            ["id" => 768, "state_id" => 15,"name" => "Tejupilco", "activo" => true,],
            ["id" => 769, "state_id" => 15,"name" => "Temamatla", "activo" => true,],
            ["id" => 770, "state_id" => 15,"name" => "Temascalapa", "activo" => true,],
            ["id" => 771, "state_id" => 15,"name" => "Temascalcingo", "activo" => true,],
            ["id" => 772, "state_id" => 15,"name" => "Temascaltepec", "activo" => true,],
            ["id" => 773, "state_id" => 15,"name" => "Temoaya", "activo" => true,],
            ["id" => 774, "state_id" => 15,"name" => "Tenancingo", "activo" => true,],
            ["id" => 775, "state_id" => 15,"name" => "Tenango del Aire", "activo" => true,],
            ["id" => 776, "state_id" => 15,"name" => "Tenango del Valle", "activo" => true,],
            ["id" => 777, "state_id" => 15,"name" => "Teoloyucán", "activo" => true,],
            ["id" => 778, "state_id" => 15,"name" => "Teotihuacán", "activo" => true,],
            ["id" => 779, "state_id" => 15,"name" => "Tepetlaoxtoc", "activo" => true,],
            ["id" => 780, "state_id" => 15,"name" => "Tepetlixpa", "activo" => true,],
            ["id" => 781, "state_id" => 15,"name" => "Tepotzotlán", "activo" => true,],
            ["id" => 782, "state_id" => 15,"name" => "Tequixquiac", "activo" => true,],
            ["id" => 783, "state_id" => 15,"name" => "Texcaltitlán", "activo" => true,],
            ["id" => 784, "state_id" => 15,"name" => "Texcalyacac", "activo" => true,],
            ["id" => 785, "state_id" => 15,"name" => "Texcoco", "activo" => true,],
            ["id" => 786, "state_id" => 15,"name" => "Tezoyuca", "activo" => true,],
            ["id" => 787, "state_id" => 15,"name" => "Tianguistenco", "activo" => true,],
            ["id" => 788, "state_id" => 15,"name" => "Timilpan", "activo" => true,],
            ["id" => 789, "state_id" => 15,"name" => "Tlalmanalco", "activo" => true,],
            ["id" => 790, "state_id" => 15,"name" => "Tlalnepantla de Baz", "activo" => true,],
            ["id" => 791, "state_id" => 15,"name" => "Tlatlaya", "activo" => true,],
            ["id" => 792, "state_id" => 15,"name" => "Toluca", "activo" => true,],
            ["id" => 793, "state_id" => 15,"name" => "Tonanitla", "activo" => true,],
            ["id" => 794, "state_id" => 15,"name" => "Tonatico", "activo" => true,],
            ["id" => 795, "state_id" => 15,"name" => "Tultepec", "activo" => true,],
            ["id" => 796, "state_id" => 15,"name" => "Tultitlán", "activo" => true,],
            ["id" => 797, "state_id" => 15,"name" => "Valle de Bravo", "activo" => true,],
            ["id" => 798, "state_id" => 15,"name" => "Valle de Chalco Solidaridad", "activo" => true,],
            ["id" => 799, "state_id" => 15,"name" => "Villa de Allende", "activo" => true,],
            ["id" => 800, "state_id" => 15,"name" => "Villa del Carbón", "activo" => true,],
            ["id" => 801, "state_id" => 15,"name" => "Villa Guerrero", "activo" => true,],
            ["id" => 802, "state_id" => 15,"name" => "Villa Victoria", "activo" => true,],
            ["id" => 803, "state_id" => 15,"name" => "Xalatlaco", "activo" => true,],
            ["id" => 804, "state_id" => 15,"name" => "Xonacatlán", "activo" => true,],
            ["id" => 805, "state_id" => 15,"name" => "Zacazonapan", "activo" => true,],
            ["id" => 806, "state_id" => 15,"name" => "Zacualpan", "activo" => true,],
            ["id" => 807, "state_id" => 15,"name" => "Zinacantepec", "activo" => true,],
            ["id" => 808, "state_id" => 15,"name" => "Zumpahuacán", "activo" => true,],
            ["id" => 809, "state_id" => 15,"name" => "Zumpango", "activo" => true,],
            ["id" => 810, "state_id" => 16,"name" => "Acuitzio", "activo" => true,],
            ["id" => 811, "state_id" => 16,"name" => "Aguililla", "activo" => true,],
            ["id" => 812, "state_id" => 16,"name" => "Alvaro Obregón", "activo" => true,],
            ["id" => 813, "state_id" => 16,"name" => "Angamacutiro", "activo" => true,],
            ["id" => 814, "state_id" => 16,"name" => "Angangueo", "activo" => true,],
            ["id" => 815, "state_id" => 16,"name" => "Apatzingán", "activo" => true,],
            ["id" => 816, "state_id" => 16,"name" => "Aporo", "activo" => true,],
            ["id" => 817, "state_id" => 16,"name" => "Aquila", "activo" => true,],
            ["id" => 818, "state_id" => 16,"name" => "Ario", "activo" => true,],
            ["id" => 819, "state_id" => 16,"name" => "Arteaga", "activo" => true,],
            ["id" => 820, "state_id" => 16,"name" => "Briseñas", "activo" => true,],
            ["id" => 821, "state_id" => 16,"name" => "Buenavista", "activo" => true,],
            ["id" => 822, "state_id" => 16,"name" => "Carácuaro", "activo" => true,],
            ["id" => 823, "state_id" => 16,"name" => "Charapan", "activo" => true,],
            ["id" => 824, "state_id" => 16,"name" => "Charo", "activo" => true,],
            ["id" => 825, "state_id" => 16,"name" => "Chavinda", "activo" => true,],
            ["id" => 826, "state_id" => 16,"name" => "Cherán", "activo" => true,],
            ["id" => 827, "state_id" => 16,"name" => "Chilchota", "activo" => true,],
            ["id" => 828, "state_id" => 16,"name" => "Chinicuila", "activo" => true,],
            ["id" => 829, "state_id" => 16,"name" => "Chucándiro", "activo" => true,],
            ["id" => 830, "state_id" => 16,"name" => "Churintzio", "activo" => true,],
            ["id" => 831, "state_id" => 16,"name" => "Churumuco", "activo" => true,],
            ["id" => 832, "state_id" => 16,"name" => "Coahuayana", "activo" => true,],
            ["id" => 833, "state_id" => 16,"name" => "Coalcomán de Vázquez Pallares", "activo" => true,],
            ["id" => 834, "state_id" => 16,"name" => "Coeneo", "activo" => true,],
            ["id" => 835, "state_id" => 16,"name" => "Cojumatlán de Régules", "activo" => true,],
            ["id" => 836, "state_id" => 16,"name" => "Contepec", "activo" => true,],
            ["id" => 837, "state_id" => 16,"name" => "Copándaro", "activo" => true,],
            ["id" => 838, "state_id" => 16,"name" => "Cotija", "activo" => true,],
            ["id" => 839, "state_id" => 16,"name" => "Cuitzeo", "activo" => true,],
            ["id" => 840, "state_id" => 16,"name" => "Ecuandureo", "activo" => true,],
            ["id" => 841, "state_id" => 16,"name" => "Epitacio Huerta", "activo" => true,],
            ["id" => 842, "state_id" => 16,"name" => "Erongarícuaro", "activo" => true,],
            ["id" => 843, "state_id" => 16,"name" => "Gabriel Zamora", "activo" => true,],
            ["id" => 844, "state_id" => 16,"name" => "Hidalgo", "activo" => true,],
            ["id" => 845, "state_id" => 16,"name" => "Huandacareo", "activo" => true,],
            ["id" => 846, "state_id" => 16,"name" => "Huaniqueo", "activo" => true,],
            ["id" => 847, "state_id" => 16,"name" => "Huetamo", "activo" => true,],
            ["id" => 848, "state_id" => 16,"name" => "Huiramba", "activo" => true,],
            ["id" => 849, "state_id" => 16,"name" => "Indaparapeo", "activo" => true,],
            ["id" => 850, "state_id" => 16,"name" => "Irimbo", "activo" => true,],
            ["id" => 851, "state_id" => 16,"name" => "Ixtlán", "activo" => true,],
            ["id" => 852, "state_id" => 16,"name" => "Jacona", "activo" => true,],
            ["id" => 853, "state_id" => 16,"name" => "Jiménez", "activo" => true,],
            ["id" => 854, "state_id" => 16,"name" => "Jiquilpan", "activo" => true,],
            ["id" => 855, "state_id" => 16,"name" => "José Sixto Verduzco", "activo" => true,],
            ["id" => 856, "state_id" => 16,"name" => "Juárez", "activo" => true,],
            ["id" => 857, "state_id" => 16,"name" => "Jungapeo", "activo" => true,],
            ["id" => 858, "state_id" => 16,"name" => "La Huacana", "activo" => true,],
            ["id" => 859, "state_id" => 16,"name" => "La Piedad", "activo" => true,],
            ["id" => 860, "state_id" => 16,"name" => "Lagunillas", "activo" => true,],
            ["id" => 861, "state_id" => 16,"name" => "Lázaro Cárdenas", "activo" => true,],
            ["id" => 862, "state_id" => 16,"name" => "Los Reyes", "activo" => true,],
            ["id" => 863, "state_id" => 16,"name" => "Madero", "activo" => true,],
            ["id" => 864, "state_id" => 16,"name" => "Maravatío", "activo" => true,],
            ["id" => 865, "state_id" => 16,"name" => "Marcos Castellanos", "activo" => true,],
            ["id" => 866, "state_id" => 16,"name" => "Morelia", "activo" => true,],
            ["id" => 867, "state_id" => 16,"name" => "Morelos", "activo" => true,],
            ["id" => 868, "state_id" => 16,"name" => "Múgica", "activo" => true,],
            ["id" => 869, "state_id" => 16,"name" => "Nahuatzen", "activo" => true,],
            ["id" => 870, "state_id" => 16,"name" => "Nocupétaro", "activo" => true,],
            ["id" => 871, "state_id" => 16,"name" => "Nuevo Parangaricutiro", "activo" => true,],
            ["id" => 872, "state_id" => 16,"name" => "Nuevo Urecho", "activo" => true,],
            ["id" => 873, "state_id" => 16,"name" => "Numarán", "activo" => true,],
            ["id" => 874, "state_id" => 16,"name" => "Ocampo", "activo" => true,],
            ["id" => 875, "state_id" => 16,"name" => "Pajacuarán", "activo" => true,],
            ["id" => 876, "state_id" => 16,"name" => "Panindícuaro", "activo" => true,],
            ["id" => 877, "state_id" => 16,"name" => "Paracho", "activo" => true,],
            ["id" => 878, "state_id" => 16,"name" => "Parácuaro", "activo" => true,],
            ["id" => 879, "state_id" => 16,"name" => "Pátzcuaro", "activo" => true,],
            ["id" => 880, "state_id" => 16,"name" => "Penjamillo", "activo" => true,],
            ["id" => 881, "state_id" => 16,"name" => "Peribán", "activo" => true,],
            ["id" => 882, "state_id" => 16,"name" => "Purépero", "activo" => true,],
            ["id" => 883, "state_id" => 16,"name" => "Puruándiro", "activo" => true,],
            ["id" => 884, "state_id" => 16,"name" => "Queréndaro", "activo" => true,],
            ["id" => 885, "state_id" => 16,"name" => "Quiroga", "activo" => true,],
            ["id" => 886, "state_id" => 16,"name" => "Sahuayo", "activo" => true,],
            ["id" => 887, "state_id" => 16,"name" => "Salvador Escalante", "activo" => true,],
            ["id" => 888, "state_id" => 16,"name" => "San Lucas", "activo" => true,],
            ["id" => 889, "state_id" => 16,"name" => "Santa Ana Maya", "activo" => true,],
            ["id" => 890, "state_id" => 16,"name" => "Senguio", "activo" => true,],
            ["id" => 891, "state_id" => 16,"name" => "Susupuato", "activo" => true,],
            ["id" => 892, "state_id" => 16,"name" => "Tacámbaro", "activo" => true,],
            ["id" => 893, "state_id" => 16,"name" => "Tancítaro", "activo" => true,],
            ["id" => 894, "state_id" => 16,"name" => "Tangamandapio", "activo" => true,],
            ["id" => 895, "state_id" => 16,"name" => "Tangancícuaro", "activo" => true,],
            ["id" => 896, "state_id" => 16,"name" => "Tanhuato", "activo" => true,],
            ["id" => 897, "state_id" => 16,"name" => "Taretan", "activo" => true,],
            ["id" => 898, "state_id" => 16,"name" => "Tarímbaro", "activo" => true,],
            ["id" => 899, "state_id" => 16,"name" => "Tepalcatepec", "activo" => true,],
            ["id" => 900, "state_id" => 16,"name" => "Tingüindín", "activo" => true,],
            ["id" => 901, "state_id" => 16,"name" => "Tingambato", "activo" => true,],
            ["id" => 902, "state_id" => 16,"name" => "Tiquicheo de Nicolás Romero", "activo" => true,],
            ["id" => 903, "state_id" => 16,"name" => "Tlalpujahua", "activo" => true,],
            ["id" => 904, "state_id" => 16,"name" => "Tlazazalca", "activo" => true,],
            ["id" => 905, "state_id" => 16,"name" => "Tocumbo", "activo" => true,],
            ["id" => 906, "state_id" => 16,"name" => "Tumbiscatío", "activo" => true,],
            ["id" => 907, "state_id" => 16,"name" => "Turicato", "activo" => true,],
            ["id" => 908, "state_id" => 16,"name" => "Tuxpan", "activo" => true,],
            ["id" => 909, "state_id" => 16,"name" => "Tuzantla", "activo" => true,],
            ["id" => 910, "state_id" => 16,"name" => "Tzintzuntzan", "activo" => true,],
            ["id" => 911, "state_id" => 16,"name" => "Tzitzio", "activo" => true,],
            ["id" => 912, "state_id" => 16,"name" => "Uruapan", "activo" => true,],
            ["id" => 913, "state_id" => 16,"name" => "Venustiano Carranza", "activo" => true,],
            ["id" => 914, "state_id" => 16,"name" => "Villamar", "activo" => true,],
            ["id" => 915, "state_id" => 16,"name" => "Vista Hermosa", "activo" => true,],
            ["id" => 916, "state_id" => 16,"name" => "Yurécuaro", "activo" => true,],
            ["id" => 917, "state_id" => 16,"name" => "Zacapu", "activo" => true,],
            ["id" => 918, "state_id" => 16,"name" => "Zamora", "activo" => true,],
            ["id" => 919, "state_id" => 16,"name" => "Zináparo", "activo" => true,],
            ["id" => 920, "state_id" => 16,"name" => "Zinapécuaro", "activo" => true,],
            ["id" => 921, "state_id" => 16,"name" => "Ziracuaretiro", "activo" => true,],
            ["id" => 922, "state_id" => 16,"name" => "Zitácuaro", "activo" => true,],
            ["id" => 923, "state_id" => 17,"name" => "Amacuzac", "activo" => true,],
            ["id" => 924, "state_id" => 17,"name" => "Atlatlahucan", "activo" => true,],
            ["id" => 925, "state_id" => 17,"name" => "Axochiapan", "activo" => true,],
            ["id" => 926, "state_id" => 17,"name" => "Ayala", "activo" => true,],
            ["id" => 927, "state_id" => 17,"name" => "Coatlán del Río", "activo" => true,],
            ["id" => 928, "state_id" => 17,"name" => "Cuautla", "activo" => true,],
            ["id" => 929, "state_id" => 17,"name" => "Cuernavaca", "activo" => true,],
            ["id" => 930, "state_id" => 17,"name" => "Emiliano Zapata", "activo" => true,],
            ["id" => 931, "state_id" => 17,"name" => "Huitzilac", "activo" => true,],
            ["id" => 932, "state_id" => 17,"name" => "Jantetelco", "activo" => true,],
            ["id" => 933, "state_id" => 17,"name" => "Jiutepec", "activo" => true,],
            ["id" => 934, "state_id" => 17,"name" => "Jojutla", "activo" => true,],
            ["id" => 935, "state_id" => 17,"name" => "Jonacatepec", "activo" => true,],
            ["id" => 936, "state_id" => 17,"name" => "Mazatepec", "activo" => true,],
            ["id" => 937, "state_id" => 17,"name" => "Miacatlán", "activo" => true,],
            ["id" => 938, "state_id" => 17,"name" => "Ocuituco", "activo" => true,],
            ["id" => 939, "state_id" => 17,"name" => "Puente de Ixtla", "activo" => true,],
            ["id" => 940, "state_id" => 17,"name" => "Temixco", "activo" => true,],
            ["id" => 941, "state_id" => 17,"name" => "Temoac", "activo" => true,],
            ["id" => 942, "state_id" => 17,"name" => "Tepalcingo", "activo" => true,],
            ["id" => 943, "state_id" => 17,"name" => "Tepoztlán", "activo" => true,],
            ["id" => 944, "state_id" => 17,"name" => "Tetecala", "activo" => true,],
            ["id" => 945, "state_id" => 17,"name" => "Tetela del Volcán", "activo" => true,],
            ["id" => 946, "state_id" => 17,"name" => "Tlalnepantla", "activo" => true,],
            ["id" => 947, "state_id" => 17,"name" => "Tlaltizapán", "activo" => true,],
            ["id" => 948, "state_id" => 17,"name" => "Tlaquiltenango", "activo" => true,],
            ["id" => 949, "state_id" => 17,"name" => "Tlayacapan", "activo" => true,],
            ["id" => 950, "state_id" => 17,"name" => "Totolapan", "activo" => true,],
            ["id" => 951, "state_id" => 17,"name" => "Xochitepec", "activo" => true,],
            ["id" => 952, "state_id" => 17,"name" => "Yautepec", "activo" => true,],
            ["id" => 953, "state_id" => 17,"name" => "Yecapixtla", "activo" => true,],
            ["id" => 954, "state_id" => 17,"name" => "Zacatepec de Hidalgo", "activo" => true,],
            ["id" => 955, "state_id" => 17,"name" => "Zacualpan de Amilpas", "activo" => true,],
            ["id" => 956, "state_id" => 18,"name" => "Acaponeta", "activo" => true,],
            ["id" => 957, "state_id" => 18,"name" => "Ahuacatlán", "activo" => true,],
            ["id" => 958, "state_id" => 18,"name" => "Amatlán de Cañas", "activo" => true,],
            ["id" => 959, "state_id" => 18,"name" => "Bahía de Banderas", "activo" => true,],
            ["id" => 960, "state_id" => 18,"name" => "Compostela", "activo" => true,],
            ["id" => 961, "state_id" => 18,"name" => "Del Nayar", "activo" => true,],
            ["id" => 962, "state_id" => 18,"name" => "Huajicori", "activo" => true,],
            ["id" => 963, "state_id" => 18,"name" => "Ixtlán del Río", "activo" => true,],
            ["id" => 964, "state_id" => 18,"name" => "Jala", "activo" => true,],
            ["id" => 965, "state_id" => 18,"name" => "La Yesca", "activo" => true,],
            ["id" => 966, "state_id" => 18,"name" => "Rosamorada", "activo" => true,],
            ["id" => 967, "state_id" => 18,"name" => "Ruíz", "activo" => true,],
            ["id" => 968, "state_id" => 18,"name" => "San Blas", "activo" => true,],
            ["id" => 969, "state_id" => 18,"name" => "San Pedro Lagunillas", "activo" => true,],
            ["id" => 970, "state_id" => 18,"name" => "Santa María del Oro", "activo" => true,],
            ["id" => 971, "state_id" => 18,"name" => "Santiago Ixcuintla", "activo" => true,],
            ["id" => 972, "state_id" => 18,"name" => "Tecuala", "activo" => true,],
            ["id" => 973, "state_id" => 18,"name" => "Tepic", "activo" => true,],
            ["id" => 974, "state_id" => 18,"name" => "Tuxpan", "activo" => true,],
            ["id" => 975, "state_id" => 18,"name" => "Xalisco", "activo" => true,],
            ["id" => 976, "state_id" => 19,"name" => "Abasolo", "activo" => true,],
            ["id" => 977, "state_id" => 19,"name" => "Agualeguas", "activo" => true,],
            ["id" => 978, "state_id" => 19,"name" => "Allende", "activo" => true,],
            ["id" => 979, "state_id" => 19,"name" => "Anáhuac", "activo" => true,],
            ["id" => 980, "state_id" => 19,"name" => "Apodaca", "activo" => true,],
            ["id" => 981, "state_id" => 19,"name" => "Aramberri", "activo" => true,],
            ["id" => 982, "state_id" => 19,"name" => "Bustamante", "activo" => true,],
            ["id" => 983, "state_id" => 19,"name" => "Cadereyta Jiménez", "activo" => true,],
            ["id" => 984, "state_id" => 19,"name" => "Carmen", "activo" => true,],
            ["id" => 985, "state_id" => 19,"name" => "Cerralvo", "activo" => true,],
            ["id" => 986, "state_id" => 19,"name" => "China", "activo" => true,],
            ["id" => 987, "state_id" => 19,"name" => "Ciénega de Flores", "activo" => true,],
            ["id" => 988, "state_id" => 19,"name" => "Dr. Coss", "activo" => true,],
            ["id" => 989, "state_id" => 19,"name" => "Dr. Arroyo", "activo" => true,],
            ["id" => 990, "state_id" => 19,"name" => "Dr. González", "activo" => true,],
            ["id" => 991, "state_id" => 19,"name" => "Galeana", "activo" => true,],
            ["id" => 992, "state_id" => 19,"name" => "García", "activo" => true,],
            ["id" => 993, "state_id" => 19,"name" => "Gral. Escobedo", "activo" => true,],
            ["id" => 994, "state_id" => 19,"name" => "Gral. Terán", "activo" => true,],
            ["id" => 995, "state_id" => 19,"name" => "Gral. Treviño", "activo" => true,],
            ["id" => 996, "state_id" => 19,"name" => "Gral. Zaragoza", "activo" => true,],
            ["id" => 997, "state_id" => 19,"name" => "Gral. Zuazua", "activo" => true,],
            ["id" => 998, "state_id" => 19,"name" => "Gral. Bravo", "activo" => true,],
            ["id" => 999, "state_id" => 19,"name" => "Guadalupe", "activo" => true,],
            ["id" => 1000, "state_id" => 19,"name" => "Hidalgo", "activo" => true,],
        ];

        DB::table('municipalities')->insert($municipalities);
    
    }
}
